### ISSUE TITLE
Excel File in Appendix B section incorrect

### ISSUE THREAD

**Issue by kelpenhagen** [ritchieking/d3-book#2]
Hi Ritchie

I downloaded the excel file in appendix B from github, and looks like this is not the correct file. It has no age breakdowns. 

I found a file with age breakdowns here: [https://dl.vecnet.org/catalog/x633f1022](url), but need to find one with fertility estimates as well.

(I'm still learning about github, and am unsure about how to do a pull request / upload the file, so i apologize if this is not the right place to let you know about this.)

I've been using your book to get acquainted with D3 and it's great - thanks!

Kind Regards
Kelly
kelly@hellomister.com.au

**Comment by ritchieking** [comment]
Hey Kelly!

Thanks so much for pointing this out. I updated Appendix B with the correct Excel file. Github Issues was definitely the right place to point this out.

Glad you're enjoying the book!

Thanks again,
Ritchie
